---
# tasks file for iptables
- name: flush iptables
  shell: iptables -F

- name: open INPUT
  shell: iptables -A INPUT -j ACCEPT

- name: open OUTPUT
  shell: iptables -A OUTPUT -j ACCEPT

- name: open FORWARD
  shell: iptables -A FORWARD -j ACCEPT
