---
- hosts: all
  become: yes
  tasks:
    - include_role:
        name: fix_locale
    - include_role:
        name: add_hosts
    - include_role:
        name: set_hostname
    - include_role:
        name: install_common_packages
    - include_role:
        name: running_services

- hosts: server
  tasks:
    - include_role:
        name: config_chrony_server
    - include_role:
        name: ldap_server

- hosts: clients
  tasks:
    - include_role:
        name: config_chrony_client
