---
- hosts: all
  become: yes
  tasks:
    - include_role:
        name: fix_locale
    - include_role:
        name: add_hosts
    - include_role:
        name: set_hostname
    - include_role:
        name: install_common_packages
    - include_role:
        name: running_services
    - include_role:
        name: consul_common
    - include_role:
        name: iptables
    - include_role:
        name: firewall

- hosts: server
  become: yes
  tasks:
    - include_role:
        name: config_chrony_server
#    - include_role:
#        name: ldap_server
    - include_role:
        name: consul_server

- hosts: clients
  become: yes
  tasks:
    - include_role:
        name: config_chrony_client
    - include_role:
        name: consul_client
