---
- name: copy conf file
  template:
    src: templates/consul.conf.j2
    dest: /etc/consul/consul.json

- name: restart consul
  systemd:
    name: consul
    daemon_reload: yes
    enabled: yes
    masked: no
    state: restarted